server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass ${ORCHESTRATOR_URL};
    }

    location /ws/ {
        proxy_pass ${ORCHESTRATOR_URL};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600;
    }

    location / {
        try_files $uri /index.html;
    }
}
